name: vaccine_hk
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3
  google_maps_flutter: ^2.0.1
  equatable: ^2.0.0
  collection: ^1.14.13
  json_annotation: '>=4.0.0-nullsafety.0 <4.1.0'
  dio: # https://github.com/flutterchina/dio/issues/1002
    git:
      url: git@github.com:harsimranmaan/dio.git
      ref: null-safety
      path: dio
  fluro: ^2.0.3
  intl: ^0.17.0
  url_launcher: ^6.0.2
  auto_size_text: 3.0.0-nullsafety.0
  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  fluttertoast: ^8.0.1-nullsafety.0
  shared_preferences: ^2.0.3
#  google_mobile_ads: ^0.11.0+3
  admob_flutter: 2.0.0-nullsafety.0
  cloud_firestore: ^1.0.1

dependency_overrides:
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3
  bloc_test: ^8.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.1
  mocktail: ^0.0.1-dev.11
  integration_test: ^1.0.0
  json_serializable: '>=4.0.0-nullsafety.0 <4.1.0'
  build_runner: ^1.11.5

flutter:
  uses-material-design: true
